spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming
    username: postgres
    password: 123123
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8001
