package com.filminfopage;

import com.filminfopage.model.FilmInfo;
import com.filminfopage.repo.FilmInfoRepo;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.annotation.Rollback;

import java.util.Date;
import java.util.Calendar;

import static org.junit.jupiter.api.Assertions.assertNotEquals;

//@SpringBootTest
@DataJpaTest
@Rollback(value = true)
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class FilmInfoPageApplicationTests {

    @Autowired
    private FilmInfoRepo filmInfoRepo;

    @Autowired
    TestEntityManager testEntityManager;

    @Test
    void insertFullFilmInfoOnce() {
        FilmInfo film = new FilmInfo(
                "film",
                new Date(2012, Calendar.JUNE, 20),
                "USA",
                "horror",
                18,
                "url/myImage/url",
                "1:30:05",
                5.4F
        );

//        FilmInfo savedFilm = filmInfoRepo.save(film);
        // Save the film using the test entity manager
        FilmInfo savedFilm = testEntityManager.persist(film);

        // Get the ID of the saved film
        Long filmId = savedFilm.getId();


        // Assert that the ID is not equal to null (assuming your ID is autogenerated)
        assertNotEquals(null, filmId, "Film info was not saved with a valid ID");

    }



}
